version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-prod
    restart: always
    environment:
      NODE_ENV: production
    depends_on:
      - postgres
    networks:
      - postgres-net
    ports:
      - "3000:3000"

  postgres:
    image: postgres:14-alpine
    container_name: postgres-prod
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres-net

volumes:
  pgdata:

networks:
  postgres-net:
